<?php

namespace App\Controllers;

use App\BusinessLayer\Domain\Adapter\UserAccountResponseAdapterInterface;
use App\BusinessLayer\Domain\Repository\UserAccountRepositoryInterface;
use App\BusinessLayer\Infra\Adapter\UserAccountResponseAdapter;
use App\BusinessLayer\Infra\Repository\UserAccountRepository;
use App\BusinessLayer\Infra\Service\PersistenceInitializationService;
use App\BusinessLayer\UseCases\GetAccountBalance;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Faker\Provider\Base;
use Psr\Log\LoggerInterface;

class AccountController extends BaseController
{
    protected UserAccountRepositoryInterface $userAccountRepository;
    protected UserAccountResponseAdapterInterface $userAccountResponseAdapter;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->userAccountRepository = new UserAccountRepository($this->cacheService);
        $this->userAccountResponseAdapter = new UserAccountResponseAdapter();
        $initPersistenceService = new PersistenceInitializationService($this->userAccountRepository);
        $initPersistenceService->init();
    }

    public function getAccountBalance() {
        $accountId = $this->request->getGet("account_id");
        if (empty($accountId)) {
            return $this->response
                ->setStatusCode(ResponseInterface::HTTP_BAD_REQUEST)
                ->setBody("Missing required parameter");
        }

        $useCase = new GetAccountBalance($this->userAccountRepository);
        $getBalanceResponse = $useCase->execute($accountId);

        return $this->response
            ->setStatusCode($getBalanceResponse->getHttpStatus())
            ->setJSON($getBalanceResponse->getBody());
    }
}